### ISSUE TITLE
Metadata writing in m2aia

### ISSUE THREAD

**Issue by cKNUSPeR** [jtfcordes/M2aia#52]
Hi, i just noticed a small bug.

When i write files using the m2aia Workbench imzML Exporter function for Continuous Profile datasets, i noticed a few minor details where the metadata is not correctly parsed:

Some names of the metadata are written with the internal reference name in the name= field, leading to a mismatch with the accession and name fields.

Here is a short example from a file i generated:

```
<fileDescription>
<fileContent>
...
<cvParam cvRef="MS" accession="MS:" name="[MS:1000128] profile spectrum" value=""/>
<cvParam cvRef="IMS" accession="IMS:" name="[IMS:1000030] continuous" value=""/>
...
</fileContent>
</fileDescription>
```

Also, the offsets for x and y positions have no value written. 

```
<cvParam accession="IMS:1000053" cvRef="IMS" name="absolute position offset x" value="" unitCvRef="UO" unitAccession="UO:0000017" unitName="micrometer"/>
<cvParam accession="IMS:1000054" cvRef="IMS" name="absolute position offset y" value="" unitCvRef="UO" unitAccession="UO:0000017" unitName="micrometer"/>

```

I hope this helps improving m2aia in the future :)

**Comment by jtfcordes** [comment]
Hello, thank you very much for your feedback!
